#! /usr/bin/env bash

#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
#pgrep -x panel > /dev/null || panel &

bspc monitor -d                       1 2 3 4 5 6 7 8 9 10

bspc config border_width              2
bspc config window_gap                0

bspc config split_ratio               0.5
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config single_monocle            true

bspc config automatic_scheme spiral

# Hack to get rid of "cross cursor"
xsetroot -cursor_name                 left_ptr

#feh --bg-center ~/.bg.png --image-bg  '#fbe68a'
feh --bg-center ~/.bg.png --image-bg  '#DEF3FD'

bspc config focused_border_color      "#abfff9"
bspc config normal_border_color       "#d2d2d2"

bspc rule -a Slack                    desktop='^9'
bspc rule -a discord                  desktop='^10'
bspc rule -a Zathura                  state=tiled
bspc rule -a Alacritty:Fuzzy          state=floating

# Not working beause Spotify sets wm class too late
bspc rule -a Spotify                  desktop='^8'
